spring:
  application:
    name: product-service
server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka}
  instance:
    preferIpAddress: true